import { cdk, javascript, TextFile } from "projen";
import { GithubCredentials } from "projen/lib/github";
import { ReleaseTrigger } from "projen/lib/release";

const BIOME_JSON = `{
  "$schema": "https://biomejs.dev/schemas/2.5.8/schema.json",
  "assist": {
    "actions": {
      "source": {
        "organizeImports": {
          "level": "on",
          "options": {
            "groups": [
              {
                "type": false
              }
            ]
          }
        }
      }
    },
    "enabled": true
  },
  "files": {
    "includes": [
      "**",
      "!.projen/**",
      "!projenrc/tsconfig.json",
      "!test/tsconfig.json",
      "!tsconfig.json"
    ]
  },
  "formatter": {
    "enabled": true,
    "indentStyle": "space",
    "indentWidth": 2,
    "lineWidth": 140
  },
  "linter": {
    "enabled": true,
    "rules": {
      "preset": "recommended",
      "style": {
        "useImportType": {
          "level": "on",
          "options": {
            "style": "separatedType"
          }
        }
      }
    }
  },
  "vcs": {
    "clientKind": "git",
    "enabled": true,
    "useIgnoreFile": true
  }
}
`;

const PRE_COMMIT_CONFIG = `# ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".

repos:
- repo: https://github.com/biomejs/pre-commit
  rev: 3e8b293b5e343b39246e76fed741691f0206b3d4  # frozen: v2.5.8
  hooks:
  - id: biome-check
- repo: local
  hooks:
  - id: biome-migrate
    name: biome migrate
    entry: biome migrate --write
    language: node
    additional_dependencies: ['@biomejs/biome@2.5.8']
    files: ^\\.pre-commit-config\\.yaml$
    pass_filenames: false
`;

const project = new cdk.JsiiProject({
  author: "Max R",
  authorAddress: "mxr@users.noreply.github.com",
  authorEmail: "mxr@users.noreply.github.com",
  authorName: "Max R",
  depsUpgrade: false,
  description: "projen external project type: stack-appropriate pre-commit config, license and repo metadata for my personal repos",
  devDeps: ["constructs@10.8.1", "projen@0.101.30"],
  docgen: false,
  eslint: false,
  github: true,
  githubOptions: {
    projenCredentials: GithubCredentials.fromApp({
      appIdSecret: "APP_ID",
      privateKeySecret: "APP_PRIVATE_KEY",
    }),
  },
  jsiiVersion: "~6.0.0",
  keywords: ["projen", "projen-external-module"],
  license: "MIT",
  name: "@mxr/base",
  npmAccess: javascript.NpmAccess.RESTRICTED,
  npmRegistryUrl: "https://npm.pkg.github.com",
  npmTokenSecret: "GITHUB_TOKEN",
  packageManager: javascript.NodePackageManager.NPM,
  peerDeps: ["constructs", "projen"],
  prettier: false,
  projenrcJson: false,
  projenrcTs: true,
  releaseToNpm: true,
  releaseTrigger: ReleaseTrigger.manual(),
  repository: "https://github.com/mxr/base.git",
  repositoryUrl: "https://github.com/mxr/base.git",
});

new TextFile(project, "biome.json", { lines: BIOME_JSON.split("\n"), readonly: false });
new TextFile(project, ".pre-commit-config.yaml", { lines: PRE_COMMIT_CONFIG.split("\n"), readonly: false });

// releases are manual (see releaseTrigger above): `npx projen release` bumps,
// tags and pushes; fold the npm publish in here too so that one command does
// the whole thing. the pushed tag then triggers propagate-update.yml in CI.
project.tasks.tryFind("release")?.exec("npm publish");

project.synth();
