[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "base-copier-extensions"
version = "0.1.0"
dependencies = ["copier-template-extensions", "pyyaml"]

[tool.setuptools]
py-modules = ["extensions"]

[tool.ty.rules]
all = "error"

[tool.mypy]
check_untyped_defs = true
disallow_any_generics = true
disallow_incomplete_defs = true
disallow_untyped_defs = true
warn_redundant_casts = true
warn_unused_ignores = true

[[tool.mypy.overrides]]
disallow_untyped_defs = false
module = "testing.*"

[[tool.mypy.overrides]]
disallow_untyped_defs = false
module = "tests.*"
