// FileBase's own marker wording is fixed ("... and run \"npx projen\".") and
// points at a .projenrc.js that doesn't exist in downstream repos, so every
// generated file writes this instead of relying on it. Split so this file
// doesn't itself contain projen's marker, which projen's cleanup deletes on
// synth when mxr/base syncs itself
export const BANNER = [
  "~~",
  "Generated by projen in mxr/base. Modifications will be overwritten on the next sync. To modify properly, edit .github/base.yml and retrigger the propagate workflow in mxr/base.",
].join(" ");
