/**
 * Trailing comment on every table header and `[project]` key that base
 * manages. tombi sorts tables and keys, so a block-style
 * begin/end marker pair doesn't survive, but a trailing comment stays with
 * its line.
 */
export const MANAGED_MARKER = "# generated by mxr/base";

export type TomlValue = string | boolean | readonly TomlValue[] | { readonly [key: string]: TomlValue };

export interface ManagedTable {
  readonly name: string;

  /**
   * Render as an `[[name]]` array-of-tables entry instead of `[name]`.
   */
  readonly array?: boolean;

  readonly lines: readonly string[];
}

export interface ManagedPyproject {
  readonly tables: readonly ManagedTable[];

  /**
   * Keys set in the downstream repo's own `[project]` table, alongside the
   * keys it manages itself (e.g. `name`, `version`).
   */
  readonly projectKeys?: Readonly<Record<string, TomlValue>>;

  /**
   * Table name prefixes base owns outright, so their tables are dropped even
   * when not in `tables` (e.g. a sqlfluff table base no longer sets).
   */
  readonly ownedPrefixes?: readonly string[];
}

/**
 * `[tool.sqlfluff.<table>]` tables written into a sql stack's `pyproject.toml`,
 * keyed by the table name under `tool.sqlfluff`.
 */
const SQLFLUFF_CONFIG: Record<string, Record<string, TomlValue>> = {
  "layout.type.comma": { line_position: "leading", spacing_before: "touch" },
  "layout.type.from_clause": { keyword_line_position: "leading" },
  "layout.type.when_clause": { keyword_line_position: "leading" },
  "rules.capitalisation.functions": { extended_capitalisation_policy: "upper" },
  "rules.capitalisation.identifiers": { extended_capitalisation_policy: "lower" },
  "rules.capitalisation.keywords": { capitalisation_policy: "upper" },
  "rules.capitalisation.literals": { capitalisation_policy: "upper" },
  "rules.convention.not_equal": { preferred_not_equal_style: "c_style" },
  "rules.convention.terminator": { multiline_newline: true, require_final_semicolon: true },
  "rules.references.quoting": { prefer_quoted_keywords: true },
};

/**
 * {@link SQLFLUFF_CONFIG} as managed tables.
 */
export function sqlfluffTables(): ManagedTable[] {
  return Object.entries(SQLFLUFF_CONFIG).map(([table, values]) => ({ name: `tool.sqlfluff.${table}`, lines: tomlEntries(values) }));
}

// tombi doesn't reflow arrays, so ones holding several arrays or a multi-line string get one element per line up front
function isMultiline(value: TomlValue): boolean {
  if (typeof value === "string") {
    return value.includes("\n");
  }
  return Array.isArray(value) && (value.some(isMultiline) || (value.length > 1 && value.some(Array.isArray)));
}

export function renderTomlValue(value: TomlValue, indent = ""): string {
  if (typeof value === "string") {
    return value.includes("\n") ? `'''\n${value}'''` : JSON.stringify(value);
  }
  if (typeof value === "boolean") {
    return String(value);
  }
  if (Array.isArray(value)) {
    if (!isMultiline(value)) {
      return `[${value.map((item) => renderTomlValue(item)).join(", ")}]`;
    }
    const inner = `${indent}  `;
    return `[\n${value.map((item) => `${inner}${renderTomlValue(item, inner)},\n`).join("")}${indent}]`;
  }
  const entries = Object.entries(value);
  return entries.length > 0 ? `{ ${entries.map(([key, v]) => `${key} = ${renderTomlValue(v)}`).join(", ")} }` : "{}";
}

/**
 * One `key = value` line per entry.
 */
export function tomlEntries(values: Readonly<Record<string, TomlValue>>): string[] {
  return Object.entries(values).map(([key, value]) => `${key} = ${renderTomlValue(value)}`);
}

export function renderManagedTables(tables: readonly ManagedTable[]): string {
  return tables
    .map(({ name, array, lines }) => [`${array ? `[[${name}]]` : `[${name}]`}  ${MANAGED_MARKER}`, ...lines].join("\n"))
    .join("\n\n");
}

const TABLE_HEADER = /^\[\[?\s*([^\]]+?)\s*\]\]?/;
const KEY = /^\s*("[^"]*"|[A-Za-z0-9_-]+)\s*=/;

// net `[`/`{` minus `]`/`}` on a line, ignoring quoted strings and comments
function bracketDepth(line: string): number {
  const code = line.replace(/"(?:[^"\\]|\\.)*"|'[^']*'/g, "").replace(/#.*$/, "");
  return (code.match(/[[{]/g)?.length ?? 0) - (code.match(/[\]}]/g)?.length ?? 0);
}

/**
 * Replaces base's managed tables and `[project]` keys in an existing
 * `pyproject.toml`, leaving the rest of the file alone. The file is otherwise
 * owned by the downstream repo, so it's edited in place rather than generated
 * wholesale. Anything previously marked with {@link MANAGED_MARKER} is
 * dropped too, so a table or key base stops managing doesn't linger.
 */
export function mergePyproject(existing: string, managed: ManagedPyproject): string {
  const tableNames = new Set(managed.tables.map(({ name }) => name));
  const projectKeys = managed.projectKeys ?? {};
  const ownedPrefixes = managed.ownedPrefixes ?? [];
  const isDropped = (name: string, header: string): boolean =>
    header.includes(MANAGED_MARKER) ||
    tableNames.has(name) ||
    ownedPrefixes.some((prefix) => name === prefix || name.startsWith(`${prefix}.`));

  const kept: string[] = [];
  let hasProject = false;
  let currentTable: string | undefined;
  let droppingTable = false;
  let droppingDepth = 0;
  for (const line of existing.split("\n")) {
    const header = TABLE_HEADER.exec(line);
    if (header?.[1] !== undefined) {
      currentTable = header[1];
      droppingTable = isDropped(currentTable, line);
      droppingDepth = 0;
      if (!droppingTable && currentTable === "project") {
        hasProject = true;
        kept.push(line, ...tomlEntries(projectKeys).map((entry) => `${entry}  ${MANAGED_MARKER}`));
        continue;
      }
    }
    if (droppingTable) {
      continue;
    }
    if (droppingDepth > 0) {
      droppingDepth += bracketDepth(line);
      continue;
    }
    const key = currentTable === "project" ? KEY.exec(line)?.[1] : undefined;
    if (key !== undefined && (key in projectKeys || line.includes(MANAGED_MARKER))) {
      droppingDepth = bracketDepth(line);
      continue;
    }
    kept.push(line);
  }

  // the downstream repo owns the rest of `[project]`, so a new one's header isn't marked
  const newProject =
    !hasProject && Object.keys(projectKeys).length > 0
      ? ["[project]", ...tomlEntries(projectKeys).map((entry) => `${entry}  ${MANAGED_MARKER}`)].join("\n")
      : "";
  const rest = kept.join("\n").trim();
  return `${sortToolTables([rest, newProject, renderManagedTables(managed.tables)].filter(Boolean).join("\n\n"))}\n`;
}

function compareTableNames(a: string, b: string): number {
  const as = a.split(".");
  const bs = b.split(".");
  for (let i = 0; i < Math.min(as.length, bs.length); i++) {
    const [x = "", y = ""] = [as[i], bs[i]];
    if (x !== y) {
      return x < y ? -1 : 1;
    }
  }
  return as.length - bs.length;
}

/**
 * Moves the `[tool.*]` tables after the rest, sorted by name, which is how
 * tombi orders them. tombi formats `pyproject.toml` after the merge anyway,
 * but not a template it's rendered from (e.g. a `pyproject.mustache`).
 * Comment lines right above a header move with its table.
 */
export function sortToolTables(content: string): string {
  const preamble: string[] = [];
  const blocks: { name: string; lines: string[] }[] = [];
  for (const line of content.split("\n")) {
    const header = TABLE_HEADER.exec(line);
    const current = blocks.at(-1);
    if (header?.[1] !== undefined) {
      const previous = current?.lines ?? preamble;
      let start = previous.length;
      while (start > 0 && previous[start - 1]?.startsWith("#")) {
        start--;
      }
      blocks.push({ name: header[1], lines: [...previous.splice(start), line] });
    } else {
      (current?.lines ?? preamble).push(line);
    }
  }
  const isTool = (name: string): boolean => name === "tool" || name.startsWith("tool.");
  const ordered = [
    ...blocks.filter(({ name }) => !isTool(name)),
    ...blocks.filter(({ name }) => isTool(name)).sort((a, b) => compareTableNames(a.name, b.name)),
  ];
  return [preamble.join("\n").trim(), ...ordered.map(({ lines }) => lines.join("\n").trim())].filter(Boolean).join("\n\n");
}
